disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "TheAwesomeShaz"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  # logo = "image.png"
  # secondaryLogo = "img/secondary-logo.png"
  # description = "My awesome website"
  # copyright = "Copy, _right?_ :thinking_face:"

 [params.author]
   name = "Shahbaaz Khan"
   email = "youremail@example.com"
   image = "image.png"
#   imageQuality = 96
   headline = "Professional Gamedev and Procrastinator"
#   bio = "A little bit about you"
   links = [
   { email = "https://mail.google.com/mail/?view=cm&fs=1&to=shahbaazkhanofficial@gmail.com" },
   { instagram = "https://instagram.com/the_awesome_shaz" },
   { youtube = "https://www.youtube.com/@TheAwesomeShaz" },
   { itch-io = "https://theawesomeshaz.itch.io/" },
   { discord = "https://discord.gg/CDnQu9mxgd" },
   { github = "https://github.com/TheAwesomeShaz" },
]
